x-airflow-common:
  &airflow-common
  image: apache/airflow:latest-python3.9
  build:
    context: .
    dockerfile: Dockerfile
  depends_on:
    - postgres
    - redis
  environment:
    - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
    - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
    - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://postgres:postgres@postgres:5432/airflow_blockchain
    - AIRFLOW__CORE__FERNET_KEY=oiDOlLgcmrDIvlFeq9reMaTzMSaaF18xax53rpK-Y4c=
    - AIRFLOW__CORE__LOGGING_LEVEL=DEBUG
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:postgres@postgres:5432/airflow_blockchain
    - AIRFLOW__WEBSERVER__SECRET_KEY=your_super_secret_key
  volumes:
    - ./config:/opt/airflow/config
    - ./dags:/opt/airflow/dags
    - ./data:/opt/airflow/data
    - ./etls:/opt/airflow/etls
    - ./pipelines:/opt/airflow/pipelines
    - ./plugins:/opt/airflow/plugins
    - ./tests:/opt/airflow/tests
    - ./utils:/opt/airflow/utils
    - ./requirements.txt:/opt/airflow/requirements.txt
  logging:
    options:
      max-size: 10m
      max-file: "2"


services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: airflow_blockchain
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    logging:
      options:
        max-size: 10m
        max-file: "3"

  airflow-init:
    <<: *airflow-common
    command: >
      bash -c "pip install -r /opt/airflow/requirements.txt && airflow db init && airflow db upgrade && airflow users create --username admin --firstname admin --lastname admin --role Admin --email airflow@airflow.com --password admin"
    restart: "no"

  webserver:
      command: webserver
      <<: *airflow-common
      ports:
        - "8080:8080"



  airflow-scheduler:
    <<: *airflow-common
    command: scheduler

  airflow-worker:
    <<: *airflow-common
    command: celery worker